import type { PlaylistItem, PlaylistItem_Tag } from "@/types";

export const savedVideoTags: Record<
  PlaylistItem["snippet"]["resourceId"]["videoId"],
  PlaylistItem_Tag[]
> = {
  "76FmdPNfk0k": ["fav", "clip", "silly"],
  jQLyNVbSaW8: ["music", "art"],
  J_p48dxG5E0: ["art", "fav"],
  KLLx2rdiqH4: ["clip", "silly"],
  osTii62YJtY: ["art"],
  "kb-Le_XFrtk": ["music", "fav"],
  XzkNg89Cq9Y: ["fav", "music", "art"],
  DTQRFoS62nQ: ["silly", "clip"],
  "5Duje_sZko8": ["music"],
  "TXfXO-FW7AY": ["lengthy", "music"],
  aHj8YOtJQMI: ["music"],
  YWAfJffxDM8: ["fav", "music"],
  "afkr7qm-E0U": ["silly", "music"],
  QQC4PKXIWyA: ["music"],
  VOChndxKi6U: ["music", "fav"],
  xv7hJ32xK94: ["music"],
  "9lxqrgViCXk": ["music"],
  "2r8srgpUlTM": ["music"],
  SVvYL0Oe2EY: ["music"],
  qjV82EmEKUA: ["music"],
  ZYYOp0CHyDI: ["music", "fav"],
  uG_3ItnCtLk: ["music", "fav"],
  "xxzw7-sCdnQ": ["music"],
  "7o8c_p2DWF0": ["silly"],
  iR20xeZ3olU: ["music", "fav"],
  K5DzlVkhdNY: ["silly", "art"],
  qXRyJO33MD4: ["music", "fav"],
  kbNdx0yqbZE: ["music"],
  KZfYDD4HHWM: ["music", "fav"],
  hvK8yLNTnXM: ["art"],
  bxVTrX8TjrU: ["music"],
  DBxbBsGFJGA: ["music", "fav"],
  "m94ftm-_kcI": ["music"],
  "8itIwVBu6os": ["music", "fav"],
  "2kEwsxRzhNQ": ["music", "fav"],
  StjW_iuFln4: ["silly"],
  "v5-R75s8ud0": ["music", "fav"],
  rOOloM27AFM: ["music"],
  yWZiJHLWhco: ["art"],
  Y6GeImJ6AxY: ["silly"],
  gQhW1RE_WWY: ["music", "fav"],
  qJFv3JkAAWk: ["music"],
  "cP3ubbn0-fY": ["music"],
  XOByedyIs00: ["art"],
  PNhqtZhM3z0: ["art", "fav", "silly"],
  OOdxuQS0iaM: ["silly"],
  PxGNt2TdXLM: ["silly", "fav"],
  RY8fsQ8CEDE: ["music", "fav"],
  RJXALPS3cl0: ["music", "fav"],
  N06fZxoUQx0: ["silly"],
  kGNCT2rPEVw: ["lengthy", "music"],
  Ny0YzejpJ7k: ["silly", "fav"],
  "4P8lm61vvnQ": ["music", "fav", "silly"],
  mAed6z6Qdos: ["silly"],
  T26Yaw9nw4I: ["clip", "silly"],
  "4Hq53bN34_w": ["silly", "fav"],
  zFlOa0PoZig: ["silly", "fav"],
  ZbKQbaYN6oc: ["silly"],
  oiIOPefKho0: ["silly", "fav"],
  qXZX1iIyxPw: ["silly", "fav"],
  "55YNSumOgIs": ["art"],
  DUNH6B0fyGg: ["music"],
  ouJJKAz0cxs: ["music", "fav"],
  "GxW-HLxXsH4": ["art", "fav", "silly"],
  ZOFoqyKznkY: ["music", "fav"],
  "6By0CWJYI_Q": ["music", "fav"],
  kzA0KpdRFnI: ["music"],
  "k1D-7WqG4UQ": ["music", "fav"],
  aA2mcpq3KaY: ["music"],
  z7Jp57I73wQ: ["clip", "silly"],
  BQS57GsE7UQ: ["music", "fav"],
  lizQBukq0ic: ["music"],
  L6xqoh8SRJc: ["music", "fav"],
  U6jQbe_BuUc: ["music", "fav"],
  UYEZL13MUFk: ["music", "fav"],
  a5ILDLnheng: ["art", "silly"],
  "8ljg2IaTDvg": ["music"],
  jCy9lWC3cOk: ["art"],
  Rm1jC0u6zSs: ["music", "fav"],
  Bdp3g8Qa148: ["music", "fav"],
  zxYdPypVQvQ: ["music", "fav"],
  loZfbaVHeO4: ["clip", "fav", "silly"],
  "RRq4-uktHiI": ["music", "silly"],
  Qf0eZH0mzhg: ["music", "fav", "silly"],
  emrtfSa3hAc: ["art", "fav"],
  "Nlw4-BDlibA": ["music", "silly"],
  "6Y4b25CYkkg": ["music", "silly"],
  xs_OxX5TEW8: ["silly"],
  VZ3DsLtrgKY: ["silly", "clip"],
  CUQVnUYfSqY: ["music", "fav"],
  Amdy8CE2Hfo: ["music", "fav"],
  JYzlbVtHt5A: ["art", "silly"],
  qNF_Z9QEBMU: ["music", "fav"],
  "pyb5slW-etU": ["music"],
  H_3N6iUh0cc: ["music"],
  G7NU3KQ4fAw: ["music", "fav"],
  MdYltIUhw2c: ["music"],
  GIb7aBzGB2M: ["music"],
  "3jd50SqqKxI": ["music"],
  gEIRQipvyYk: ["silly", "clip"],
  iwfui1__Ceo: ["music", "fav"],
  "JlFBn-uMMac": ["silly"],
  QYEF6ubr4IE: ["art", "silly"],
  Pl1dPRX_Kik: ["music", "fav"],
  facaJhr4Fvk: ["art", "silly"],
  "q7gy2GRwT-I": ["fav", "silly"],
  PCYt3lPGnnc: ["silly", "fav", "art"],
  vcQvyLm1eHw: ["art"],
  wx2x06kdUGY: ["music", "fav"],
  nAL13P37dqI: ["silly", "music"],
  "xnX8Lk-iSCo": ["music"],
  "-AhIdFW7Qwc": ["silly", "fav"],
  "2LtxK81HBK8": ["fav", "clip", "silly"],
  kurAJvAHB6I: ["silly", "fav"],
  "UmN7Fr_Kf-8": ["music", "fav"],
  "60VJqZw16c8": ["music", "fav"],
  wY6K8nIlk8Y: ["art", "silly"],
  zZXW_iXIrss: ["music", "fav"],
  DNX09ZN0zuI: ["music", "fav"],
  _XrwVHxVktc: ["art"],
  bmT_cEfOTJE: ["music"],
  UFRIsspP9UE: ["music"],
  lHE1y7OCg14: ["music", "fav"],
  B_N1uEAHk10: ["music"],
  TQMMDt4yyXs: ["music", "fav"],
  UJ3kOYor8EY: ["art", "fav"],
  OcImO0AOQvc: ["art", "silly"],
  EaKz6FfzfMQ: ["music"],
  "4W77IopFWi8": ["music"],
  slIpz89oevA: ["clip", "silly"],
  C_8wlGPMx1s: ["art", "silly"],
  "CYs5-6SWkng": ["art"],
  oXnPejqAAsE: ["music", "fav"],
  eVy73aeT4n0: ["lengthy", "music"],
  OgQc2wSjy3c: ["music", "fav", "art"],
  M_eHBRYenTs: ["music"],
  ciO5j4XThiU: ["music", "fav"],
  KXawOV9R4mg: ["music"],
  VqzJiw5xwFk: ["music", "fav"],
  FSLxRRQdNs4: ["music"],
  vmjFFKTSNEw: ["art", "fav", "silly"],
  sMcfFmR0MmA: ["clip", "fav", "silly"],
  f5qjcOA2u0A: ["clip", "fav", "silly"],
  ISxwk11pimE: ["clip", "silly"],
  EdFaUNE17Fg: ["lengthy", "music"],
  cUic4BpbzHI: ["music", "fav", "art"],
  O34COqcLqWc: ["music", "art", "fav"],
  kZo3pCWI8go: ["music", "fav"],
  "92U96iNWY24": ["silly", "fav"],
  "5SAaYmlD02s": ["clip", "silly"],
  Fwa1d_VDcR8: ["fav", "clip", "silly"],
  KF9Mu2gXNdI: ["music", "art"],
  GTlQhMRHXIg: ["music"],
  "HOz-9FzIDf0": ["music", "fav"],
  "1gywabi-I4k": ["music", "fav"],
  ksJmpZB7X1I: ["clip", "fav", "silly"],
  "7WryveKlyX8": ["music", "art", "fav"],
  kXBCbegR2Eo: ["clip", "silly"],
  CEUxRBX32hU: ["clip", "silly"],
  H2eUz5k0Yhw: ["silly"],
  XmMz_eUw038: ["art"],
  "vdqVZq-6EbI": ["music"],
  vbbbChpWqoQ: ["music", "fav"],
  zFnkbGi8jEk: ["art", "fav"],
  yXIypEB4hvE: ["music", "fav", "art"],
  wy0VmcUQcPk: ["music"],
  "3kZD1oNxLA0": ["art", "fav"],
  "91E_W8JhSjs": ["music"],
  "3-AjwRWH788": ["music"],
  "cnn-e8dsajE": ["music", "fav"],
  nMLIBwSbOxE: ["music", "fav"],
  "2x12rSJHU3A": ["music"],
  "5LxGowE5ju4": ["music", "fav"],
  y4Kz44WJhdQ: ["lengthy", "music", "fav"],
  ieTX3SU8Qx8: ["music", "fav"],
  "I-dau-DJS18": ["music", "art", "fav"],
  MvZFESipgMc: ["music"],
  "7HiQQUqTM90": ["music", "fav"],
  "7P1u924OthQ": ["music"],
  "ySC2vP-pcss": ["music"],
  "Dq-qB6UDUG4": ["clip", "silly"],
  xbKL6XMiXxM: ["music", "fav"],
  oUUCJ9_DLS4: ["lengthy", "music"],
  hzRBNtvfFfg: ["art"],
  "2aWGd-WWs5A": ["clip", "silly"],
  xTax3vUsOp0: ["music", "art", "fav"],
  w0XGdRBOE_4: ["clip", "fav"],
  i5B5uSPaPLo: ["silly", "fav", "clip"],
  GRuvplJO044: ["fav", "silly", "clip"],
  jT4YqySCkD4: ["music", "art"],
  "C1pKOoW-nIY": ["music"],
  KwPUiyj0LrE: ["art", "silly"],
  zeEcERSmFp8: ["music"],
  "yt-5cn6CH4c": ["music", "fav"],
  FJPwQytrb6M: ["music", "fav"],
  "8bkICbOt1ck": ["music", "fav"],
  AU2uzp10lGo: ["art", "fav", "silly"],
  P713lMI2_5E: ["music", "fav"],
  Bo7E3nxVpTY: ["music", "fav"],
  "KBpu-1E7Spc": ["art", "fav"],
  si6F59Y5KRU: ["art", "fav", "silly"],
  UkoXbma0mIc: ["music", "fav"],
  jN5DpRT9Ho0: ["music", "fav"],
  QwNeP97hFS0: ["clip", "silly"],
  hFBn_Ro9y7I: ["lengthy", "music"],
  P5k2Db1SRrY: ["silly", "music"],
  M7VSEZOQIlg: ["music", "art", "fav"],
  atsMD_C0N9s: ["clip"],
  uw46ux9_Pcw: ["art", "fav"],
  p_qbnlVgJK0: ["silly", "music"],
  KyW92Y568g8: ["art", "fav"],
  YUMhTFTKjTw: ["silly", "art", "music"],
  OTLGWNruuOE: ["lengthy", "fav", "art"],
  jc9oJjfOh34: ["music", "fav"],
  U7Lkc3hzE0w: ["art", "fav", "silly"],
  "7IUi0htUnuE": ["music", "fav"],
  wVVmEN3m5tQ: ["music", "art", "fav"],
  "ShcUKzHQf-4": ["music"],
  anJrjWw6zQA: ["music"],
  oT_oXm1nxWw: ["clip"],
  KVwqicES0FE: ["art", "fav"],
  C9z7BxiUGu8: ["silly", "clip"],
  m9YeFINPoio: ["clip", "silly"],
  LQXawmhfMtg: ["music"],
  w7x_lWJNnNg: ["clip", "silly"],
  "FOlZYSq-UaE": ["clip", "silly"],
  HsjxARiIVSE: ["music"],
  koZHsGyg7I0: ["clip"],
  P4BHWDZUpXM: ["silly", "fav", "clip"],
  "2kr0xTvbJt0": ["music", "fav"],
  "0OPi2xx2KxA": ["music", "fav"],
  MQssmhzxxAw: ["music", "fav"],
  ISZ8lKOVapA: ["music"],
  iKfi8TvQThQ: ["music", "fav"],
  "48rSt3eM7XE": ["silly", "art", "fav"],
  Q1_mKApSiP8: ["music", "art"],
  z_Mq0p0DZ2g: ["music"],
  GK8ZFvL91Bk: ["clip", "fav", "silly"],
  lUDPjyfmJrs: ["music", "art", "fav"],
  wHCJFQQFbPM: ["music", "fav"],
  tCxnePcIa_k: ["music", "art", "fav"],
  izL_Y4JKehQ: ["silly", "fav", "art"],
  "8sgn--BI27Q": ["music", "fav"],
  vA7XQd0IlK0: ["music", "fav", "silly"],
  "Hv-H0VmXvjs": ["music"],
  pgR1V9uDMQ8: ["music", "silly"],
  YZqbp65hF_E: ["music"],
  JnQG33YftIw: ["music", "fav"],
  "34oBXNVYawc": ["silly", "fav", "clip"],
  HKpY012cK3A: ["music", "fav"],
  "3fh78wcgV2o": ["silly", "fav", "clip"],
  "pcp11ls-nrg": ["silly", "fav", "clip"],
  "TN-nGOp0Jsk": ["art", "fav", "silly"],
  gyQg9sVN7Vs: ["music"],
  "9GElj3l14mc": ["art"],
  kljtVtXIBrQ: ["clip", "fav"],
  mww4TucZZ_A: ["music", "fav"],
  "Q1J5-T8pNZA": ["music", "fav"],
  "3LGdFKIXr9I": ["music", "fav", "silly"],
  xBd07xNC2ig: ["clip", "fav", "silly"],
  uCLlfHoFVUw: ["music", "fav"],
  "0Z2-xs9nZ3E": ["clip", "silly"],
  MGFy5UAiC3g: ["silly", "clip"],
  "8GeB7xZqJ48": ["music"],
  ktzbPzmAnnw: ["music"],
  M8bZ40MG5t8: ["music", "fav"],
  iGaO9SBnFWE: ["clip"],
  M65fc_SrIaU: ["music"],
  "1NL-sIP9p_U": ["music"],
  MrEsVJk4C2g: ["music", "fav"],
  yg8dAdEJjmo: ["music", "fav"],
  "-fIfbJYCTfU": ["music"],
  NytEjY5H1EY: ["music"],
  _tioqOn3Sto: ["music", "fav"],
  wuAcfGl5Zxk: ["music"],
  "5XehRIb81k8": ["music", "fav"],
  ZLFvQWP4Yoo: ["music", "fav"],
  xyfphoTP0mQ: ["music", "art"],
  N6DMXNyvAxs: ["music", "fav", "art"],
  RYvDraBZhYI: ["music", "fav", "art"],
  KFq2TCtJDvw: ["music"],
  LeLiID3nHNM: ["music", "fav"],
  hmTRatAiBtY: ["music", "fav"],
  "W-XiSKRxrI8": ["art", "fav"],
  "v7s-gHSs-YM": ["music"],
  j3uN47eXHJo: ["music", "fav", "art"],
  TKNeu63cWR4: ["music"],
  RUh3CO2GwEE: ["music", "fav"],
  NMiQmumW0nI: ["music", "fav"],
  "19y8YTbvri8": ["music", "fav", "art"],
  NY_P9k48pnY: ["music"],
  inbpiMx0BeM: ["art", "fav", "silly"],
  KacdxoHZOtk: ["music", "fav"],
  MH78iBAKgRY: ["music", "art", "fav"],
  bmFGbBmlyKQ: ["music", "fav", "silly"],
  LP5Q7J0Zs7s: ["music"],
  "InZ7GOU-CQ8": ["music", "art"],
  FBuPc5dn9Qs: ["music", "silly"],
  g1uYKdNuAa4: ["music", "fav"],
  "rftRb-uHE00": ["music", "fav"],
  LwhVMM78RVc: ["lengthy", "fav", "music"],
  pVcaxIjVLdk: ["art", "fav", "silly"],
  "ZOOrBIK7-0A": ["clip", "silly"],
  eKzh57fh83A: ["clip", "silly"],
  _D4Y0jiYxWE: ["music", "fav"],
  h5bSMPb7pVQ: ["music", "fav"],
  wlQWPpt9lGc: ["silly", "fav", "clip"],
  CQ2IXEUCjmU: ["silly", "fav", "clip"],
  lP0CtV5QOgs: ["music", "art", "fav"],
  mh2smgh2GtA: ["music", "art", "fav"],
  Q1lNdHg1eD8: ["music", "fav"],
  _qj9ftYCNyw: ["music", "art", "fav"],
  PyxYqRqq6g0: ["art", "silly"],
  I51Wxzv0_wE: ["clip", "silly"],
  aotlEpmAFVQ: ["clip", "silly"],
  O1R166XJBJM: ["music", "fav", "silly"],
  xD_dPQGxC48: ["music", "fav"],
  FGM3U3buQj0: ["music", "fav"],
  MTxI2pZRNqc: ["music", "fav"],
  LQmJzaWUO80: ["music", "fav"],
  DdzP3Kw8Otc: ["music"],
  cfW5T38Dd84: ["silly", "fav", "clip"],
  AxE4TltnvjI: ["clip", "silly"],
  fEPIB5Owc0k: ["clip", "silly"],
  IhmMLqxWFxI: ["art", "silly"],
  kYvElHPpvzE: ["art", "silly"],
  A7eIbYvr6Ao: ["art", "fav"],
  qGZ8gakIpzg: ["music", "fav"],
  xpcazMYYZiM: ["clip", "art", "fav"],
  LF8J2IE_ZYM: ["music", "fav"],
  EAk8PjCsXQ8: ["clip", "fav", "silly"],
  "0QLft2Rh7dM": ["silly", "art", "fav", "clip"],
  "mLUQKCrbk-k": ["music", "fav"],
  "18iKpPVMba4": ["music", "fav", "silly"],
  whSaPEcKVYs: ["clip", "fav"],
  p0s0_4KO9t4: ["music", "fav", "silly"],
  "1e6b5dBGmfs": ["art", "silly"],
  j7x0rvNYCs4: ["music", "fav"],
  O65MLIQswHU: ["music", "fav"],
  l8bhdzQflyo: ["music", "fav"],
  "Qo-7487O6d4": ["music", "fav"],
  kS0hpMVQn0k: ["music", "fav"],
  MKov0tymycg: ["silly", "clip"],
  GiaD7WSdb4M: ["art", "fav", "silly"],
  PBGiQYo11IY: ["clip", "silly"],
  lIXDxGr9e90: ["music", "fav"],
  LjplmWOrHJQ: ["music", "fav"],
  neuCtK96Dww: ["music", "fav"],
  KisF4fLLlKc: ["silly", "fav", "clip"],
  SNTltkuRiqw: ["music", "fav", "silly"],
  "7h7bnYA1LXE": ["music", "fav", "silly"],
  WIOiZ3glODU: ["music", "fav"],
  WhwvIfFxP_g: ["clip", "silly"],
  miymx9wRmEE: ["music", "fav"],
  hXpuJ3J3Sx4: ["music", "art", "fav"],
  "4hvfQlZzbe0": ["music", "art", "fav"],
  PbkJaEqtj4U: ["silly", "fav", "clip"],
  EvYIYjgygy8: ["silly", "fav", "clip"],
  RmyaQrQFQ7M: ["silly", "fav", "clip"],
  YkH6y5rEwvs: ["art"],
  "229ERN1N9nQ": ["art"],
  YRajPwQOkOk: ["music", "fav", "silly"],
  "t0T-88aII1s": ["music", "fav"],
  B0uSLgW9o7E: ["music", "fav"],
  IlAjqL7qO50: ["music", "fav"],
  ZT309xXpOHo: ["music"],
  OXDLsYPp0z0: ["music", "fav"],
  "4HcK_HbtRLw": ["music", "fav"],
  xuunbl0qwH0: ["music"],
  wfrwqGLHTog: ["silly", "clip"],
  "4dHeI8NOFLQ": ["music"],
  brpKGTnkVdI: ["art", "fav"],
  YqIDl7eWmdk: ["art", "fav"],
  KBAixwe3Z80: ["clip", "fav", "silly"],
  "wLyggh--BYY": ["music", "fav"],
  "N-7gbWKbXbQ": ["clip", "fav", "silly"],
  "3j6W0RpxzEg": ["fav", "clip", "silly"],
  OqEE_A93LmI: ["silly", "clip"],
  "00qts_BPm5Y": ["art", "fav"],
  en_HZ1v1GOc: ["lengthy", "music"],
  uiGhAfVPa90: ["art", "silly"],
  omnyBfxavk8: ["music", "silly", "fav"],
  JhsEpHTCOHA: ["art", "fav", "silly"],
  eh7rvstRNTA: ["art", "fav"],
  Q4sWF6z9TuE: ["music", "art", "fav"],
  "XKcKzd0vJ-c": ["music", "fav"],
  "4o07TNTBSPw": ["clip", "silly"],
  "vYyZJFxzN-U": ["fav", "clip", "music", "silly"],
  "5PPhCIHL39U": ["silly", "fav", "clip"],
  _7GRtywPYFY: ["clip", "fav", "silly"],
  IhXkYNOf3KU: ["music", "fav"],
  xCZjc0biYAo: ["music"],
  yAcHKPXLnUY: ["music", "fav"],
  VSuHvoxbk6w: ["music", "fav"],
  AO2UkjfAoxA: ["music", "fav"],
  aM0NpYAJvjE: ["music", "fav"],
  tywYIpJKb8w: ["clip", "fav", "silly"],
  FHYU93B4XnY: ["art", "silly"],
  HgoRTk_f9LI: ["art", "silly"],
  S8Kot7Iih68: ["silly", "clip"],
  JxlEYjDzD78: ["art", "fav", "silly"],
  "_YfqYB-m1AM": ["art", "fav", "silly"],
  FWO2FVNs8DQ: ["silly", "fav", "clip"],
  PldfSwsvdWM: ["art", "fav"],
  _9WNkH3v_lo: ["silly"],
  "5qfZvz2_spE": ["art", "fav", "silly"],
  "38NjDPaYOn8": ["music"],
  Z2IHNAjrnNI: ["music", "fav"],
  "2C93pWC6OvI": ["clip", "silly"],
  "51siQz85680": ["music", "fav"],
  UGNu28SY36Q: ["music"],
  Pv1QnqHvlg0: ["silly", "fav", "clip"],
  s50vvwTystA: ["clip", "fav"],
  RWnaWpBCAC0: ["art", "fav"],
  CKR9lWFzflg: ["music"],
  OZ4Y9GlA8Yw: ["music", "fav", "art"],
  Z5NoQg8LdDk: ["music"],
  "z-3XBYnKaCU": ["music", "fav"],
  "3Awjgwc1tGo": ["music", "fav"],
  gnr8FmqdBEo: ["music", "fav"],
  "3_6M1sSm2nU": ["clip", "silly"],
  _PBzemH0D9g: ["music", "fav"],
  zlcVRM35cl8: ["music"],
  UWM5WuMDaiI: ["music"],
  _nqZc0KOc1U: ["music", "fav"],
  "7jz9P4Nofbc": ["art", "fav"],
  "nb-D7z_KVh0": ["music", "fav"],
  Szl25PBAd5c: ["music", "fav"],
  bgWeMl5qni8: ["music", "fav"],
  yyzNGmJGiY0: ["clip", "silly"],
  z3U0udLH974: ["clip", "silly"],
  LdOQ6qtoQ4I: ["clip", "silly"],
  bRrjj3ojuyQ: ["clip", "silly"],
  R2yOpkIGTeg: ["music", "lengthy", "silly"],
  "0rlS80hRIVQ": ["clip", "fav", "silly"],
  NNt2v13tS64: ["clip", "silly"],
  d4HwO3ZUCUw: ["clip", "silly"],
  "wK3U-TvX7yE": ["clip", "fav", "silly"],
  "o-AkzNb25pE": ["music", "fav"],
  Y5kj0LvHyu0: ["music", "fav"],
  tmJjidNwH_k: ["music", "fav"],
  s0jypGHFbnA: ["music", "fav", "art"],
  "8j3wK1DXhrs": ["music", "fav"],
  "9aiuzVI35BQ": ["music", "art", "fav"],
  rSKXUmJKSKI: ["clip", "silly"],
  Xfdabo27HmA: ["art", "silly"],
  rkgUtEuAHmc: ["fav", "silly", "art"],
  zCxn3Xf2LBQ: ["music"],
  "0wFhQ35C44c": ["music"],
  CwP1pT6aDcM: ["music"],
  "75ElNdDUtKs": ["music"],
  jyASj039aLE: ["art", "silly"],
  rKfSc6_9skg: ["music", "fav", "art"],
  ZmfclkgfGw0: ["music", "fav"],
  GeYqC5JlJXY: ["music", "fav"],
  lGXgYHlR8ww: ["music", "fav"],
  FJRAs4qItss: ["music", "fav"],
  IAlLkZOxO6g: ["art"],
  TNAoKLTWDFI: ["art", "silly"],
  B2aJjF1baA4: ["music", "fav", "silly"],
  "6-KukmR7vtE": ["music", "fav"],
  zk6vFVRmbnc: ["music", "fav"],
  QkdDWaBtK04: ["music"],
  Sp3hp5fqfPc: ["music"],
  "04ecSs3cPLA": ["music", "fav"],
  f4x3hTs8zhk: ["music", "fav"],
  "pLTw5mV-hkE": ["music"],
  VNW5hF3mV1g: ["music"],
  wRXAEZ0RKCw: ["music", "fav"],
  BidG5Goe4RU: ["music", "fav"],
  WqkZcmub0rk: ["art", "fav"],
  jjUzmL4yZt4: ["art", "silly"],
  "21VhD00VZIA": ["art", "fav", "silly"],
  yAXOsFNDg9Y: ["music", "fav"],
  Ko6E8gJ6Z8g: ["art"],
  xRX4gDZ2rG4: ["art", "silly"],
  cJZV2Hb6q2c: ["music"],
  VsX_M8n407k: ["silly", "fav", "clip"],
  "K-Z7o_tbBCw": ["music", "art", "fav"],
  "kX-wJ-DfNxA": ["clip", "fav"],
  Y9ZPH6pu08w: ["silly", "fav"],
  MeIr__26dAw: [],
  fOWBFZ3idS4: ["music", "fav"],
  "4vPQflSOVv4": ["music", "fav"],
  Sz1C7CO1PkM: ["art", "silly"],
  SJcgOWsDwi4: ["music", "art", "fav"],
  WXQeBeinV_8: ["music", "fav"],
  "3DcMDbBgLlQ": ["music"],
  ABPb8lnwsKs: ["art", "fav", "music"],
  aa3YPMdSdMw: ["silly", "clip"],
  "4g3L3Muoym8": ["clip", "silly"],
  DWtbMzghaMM: ["music", "fav"],
  QAioeZ3gmHg: ["music", "art", "fav"],
  "B-1jHa9gqnw": ["silly", "fav"],
  YBRCk3O0nVg: ["silly", "fav"],
  "63PuSnyDB6s": ["silly", "fav"],
  YwMai_Y_bqk: ["art", "fav"],
  "Tj27f-n7nZA": ["art"],
  jovzQ5YS63w: ["music"],
  XrfQOCl0L7o: ["clip", "art", "fav"],
  PQi_p8PCxfk: ["music", "fav"],
  lOhchf7RJUc: ["art", "fav"],
  gnMtxPsFYXg: ["music"],
  AiHCEH1lt5c: ["music"],
  "93eolMFrfVg": ["art", "fav"],
  "LxC0kD-GuBQ": ["music"],
  "5dekfK2HG0M": ["clip"],
  "8HdGH3g-NoY": ["clip", "fav"],
  oTaJU0MIYTc: ["art"],
  dvK6zX9dJ9c: ["music"],
  sF37ddmDXwg: ["silly", "clip", "music"],
  "4vqt9eYSJMo": ["silly", "clip"],
  kBep3Yw5OTg: ["music"],
  "gLhH-yM-6Eg": ["music", "fav"],
  ZmiN7egSP_Q: ["silly", "clip"],
  "Qmu-8b3HHpo": ["silly", "clip"],
  n9cdNRenBk4: ["music"],
  FNs8ldqgNck: ["music"],
  Dyia273Gi7E: ["fav", "lengthy"],
  KdrpBQGOSDQ: ["music", "fav"],
  XAaF_4sAGMY: ["silly", "clip"],
  klIxS5o65C4: ["music", "fav"],
  BwLYn8or3dw: ["music", "fav"],
  "TGJ9-1LWFtE": ["music"],
  "aYqSr9c-T6Q": ["music"],
  BC3VhlNGs64: ["music"],
  NSkC6J348eI: ["music", "fav", "clip"],
  "03iKTXFKFFU": ["music", "fav"],
  "7wFKH1rFqEQ": ["music"],
  tNkh4zkUWEs: ["music", "fav"],
  Z1fNlEsv9pk: ["silly", "clip"],
  eD81CsAFmDU: ["music", "fav"],
  kqj7b59D85Y: ["music", "fav"],
  zpJEnz6dL4Y: ["clip", "silly"],
  SiMmYlZeuOk: ["music", "fav"],
  "2PvoVV7RpyM": ["silly", "clip"],
  uvAPiELt_Oo: ["music", "fav"],
  "6AxgWd-JXvA": ["music", "fav", "art"],
  lfqk0Iq_G6g: ["clip", "silly"],
  l06dMYO_RMA: ["music", "fav"],
  NOiADZW9biM: ["music", "fav"],
  "5l8VZEyNRH8": ["fav", "music"],
  wV5V23yAQOc: ["music", "fav"],
  t_9QAp2tTaY: ["lengthy", "fav", "music"],
  "AV4c-w0OF9I": ["silly", "clip", "fav"],
  fckdimdQ2ak: ["music"],
  RqK3bGxeH98: ["music", "fav", "art"],
  XzqgSTK9RrE: ["music", "fav"],
  "JuVu-AoC5M0": ["music", "fav"],
  _bQYLXI7It4: ["music"],
  _UeSJTIJoOo: ["music"],
  tygbMYcQtNM: ["music", "fav"],
  IvxENEi1mDI: ["silly", "clip", "fav"],
  "ZkMG-XqSlYA": ["music", "fav"],
  aftOCaPnsns: ["music"],
  vIFJODP_zTE: ["music", "fav"],
  QdiqIo963PE: ["music", "fav"],
  EQWwh0VeINU: ["music", "fav"],
  "HdRSI-DsenY": ["music", "fav"],
  SEABn1jepkY: ["music", "fav"],
  RbGrWNe8h40: ["clip", "silly", "fav"],
  "-laSwHXmgM8": ["silly", "clip"],
  c56TpxfO9q0: ["music", "fav"],
  rKaNUZdXJvo: ["music", "fav"],
  TGU2UbJc9Vg: ["silly", "clip"],
  "4BVcopnpeTw": ["silly", "clip", "fav"],
  jTU8KtpFN3c: ["music", "fav"],
  zul8B399nzA: ["fav", "music"],
  UKtu33ufV5A: ["clip", "silly", "music", "fav"],
  EjEs599WEdI: ["music", "silly", "fav"],
  "24QZyTzSS00": ["clip", "fav"],
  YGkr5JE9xGY: ["music", "fav"],
  mv_WWjOcvus: ["music", "fav"],
  Y4PUHZJto1o: ["music", "fav"],
  eTplxWaAD8o: ["art", "music", "fav"],
  "3qnrewFcnQs": ["music", "fav"],
  "S-1FdrpHkxo": ["music"],
  J6HVv3Jxxlg: ["music", "fav", "art"],
  kKnkhAQxLKI: ["silly", "clip", "fav"],
  _TwYA5pkGIQ: ["music", "art", "fav"],
  "73z9ZsDK4co": ["music"],
  MJa46AEGMb4: ["music", "art", "fav"],
  "0fJSNHM1rHM": ["silly", "clip"],
  H_nM5p7o4HI: ["silly", "clip", "fav"],
  "F--zI3Nzyq8": ["clip", "silly", "art"],
  uGZ0I71Yawo: ["music", "fav", "art"],
  o5NRO4E3GzY: ["music", "fav"],
  Y0jE3O_3deI: ["music", "art", "fav"],
  "GZYbrS-Js-0": ["clip", "silly", "art"],
  apFSQhcosac: ["fav", "music"],
  Oe2KBWT43_k: ["music", "fav"],
  zXrTnnz8rP0: ["clip", "silly", "art"],
  DAcv7QxVRrI: ["clip", "silly", "art"],
  "L7C-hty7ONg": ["music", "fav"],
  "-75jUnJhHc0": ["music", "fav"],
  ndj2qYnvT_s: ["music", "fav"],
  "9ZN1_sWg0LI": ["music", "fav"],
  vWY8xBqBFEo: ["silly", "clip"],
  xQbmiAo6_qU: ["music", "fav"],
  K3FJ2Zxjn_k: ["clip", "art", "silly"],
  OspOMEdXg_Q: ["clip", "art", "fav"],
  FsSuxTm8tqY: ["art", "clip", "fav"],
  m9M9YeLDnfI: ["music", "fav"],
  "Z01EfEP-GAY": ["music"],
  "8osOUlrAX3A": ["clip", "silly", "fav"],
  jzi6RNVEOtA: ["music", "fav"],
  ZEdbSuoF7uM: ["music", "fav"],
  Fm2Foo__ZBY: ["music", "fav"],
  wH3PZuEhscE: ["music"],
  evloseZCQcc: ["music", "art", "fav"],
  "Z_fF-iwfrbI": ["music", "fav"],
  Pif6kI4T0iI: ["music", "fav"],
  cETzlmNnXgc: ["music"],
  FeIlkRCn1xw: ["silly", "clip", "fav"],
  ANGsstnQtPg: ["clip", "art", "fav"],
  "2HbhyhTWJnE": ["clip", "art", "fav"],
  KzxHqnMMq4I: ["music", "fav", "lengthy"],
  MRnMZ_YkiSM: ["music", "fav"],
  "Q8bMih46-bc": ["music", "fav"],
  "6hWEF0hbFjw": ["fav", "lengthy", "silly"],
  woS6yfosI1k: ["music", "fav"],
  "0Zlpq6ADDUk": ["clip", "music"],
  "6Bqw51Vsl78": ["music", "fav"],
  DjGxGMxvg4M: ["music", "fav", "art"],
  cTAwl49yLu4: ["music", "fav"],
  injd7gHrIGU: ["music", "fav", "art"],
  bWtWmXv1npo: ["music"],
};
